export { default as HeroSection } from './herosection/herosection'
export { default as Navbar } from './nav/nav'
export { default as Maintenance } from './maintenance/maintenance'
export { default as Socials } from './socials/socials'
export { default as LanguageSwitcher } from './langswitcher/langswitcher'
export { default as Section1a } from './section1a/section1a'
